version: 2.1

executors:
  default:
    docker:
      - image: circleci/rust:1.35

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install clippy and fmt
          command: rustup component add clippy rustfmt
      - run:
          name: Run rust format
          command: cargo fmt -- --check
      - run:
          name: Run clippy
          command: cargo clippy -- -D warnings

  build:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build all targets
          command: cargo build --all --all-targets

  test:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run all tests
          command: cargo test --all

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
