version: 2.1

executors:
  default:
    docker:
      - image: circleci/rust:1.35

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install clippy and fmt
          command: rustup component add clippy rustfmt
      - run:
          name: Run rust format
          command: cargo fmt -- --check
      - run:
          name: Run clippy
          command: cargo clippy -- -D warnings
      - persist_to_workspace:
          root: .
          paths: .

  build:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - persist_to_workspace:
          root: .
          paths: .

  test:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run all tests
          command: cargo test --all
      - persist_to_workspace:
          root: .
          paths: .

  finalize:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
      - finalize:
          requires:
            - lint
            - build
            - test
